---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reporter
rules:
  - apiGroups:
      - ""
      - extensions
      - apps
      - '*'
    resources:
      - '*'
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ""
    resources:
      - pods/portforward
    verbs:
      - '*'
