---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin
  namespace: kubetools

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reporter
  namespace: kubetools

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: kubetools