# Create a pod that reads and writes to the
# NFS server via an NFS volume.
---
kind: Pod
apiVersion: v1
metadata:
  name: dummypod
  namespace: kubetools
spec:
  # Add the server as an NFS volume for the pod
  volumes:
    - name: nfs-volume
      nfs:
        # URL for the NFS server
        server: 10.10.10.120 # Change this!
        path: /prometheus
  # In this container, we'll mount the NFS volume
  # and write the date to a file inside it.
  containers:
    - name: app
      image: ubuntu:16.04
      # Mount the NFS volume in the container
      volumeMounts:
        - name: nfs-volume
          mountPath: /var/nfs
      # Write to a file inside our NFS
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo test; sleep 5; done"]
