apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
  volumeName: "prometheus-nfs"